<footer style="margin-top:200px;">
  <!-- MainContainer -->

  <!-- AboutUs -->
  <div class="container">
    <div class="content "> 
      <h5>COCOA</h5>
      <p>Deliveres</p>
      <p>Orders</p>
      <p>Careers</p>
      <p>Portfolio</p>
    </div>

    <!-- ContactInfo -->
    <div class="content " >
      <h5>Contact Info <div class="underline"></div>
      </h5>
      <p>no.58 A,East Madision,USA</p>
      <p>0000-123-456789</p>
      <p>1800 266 0600</p>
      <p class="email-id">aabi@gmail.com</p>
    </div>

    <!--Corporate  -->
    <div class="content "style="padding-left:4%;">
      <h5>Information</h5>
      <p> Advanced  </p>
      <p>Careers</p>
      <p>Help and Faq's</p>
      <p>Store Location</p>
    </div>
    

    <!-- NewsLetter -->
    <div class="content">
      <h5>Email<div class="underline"></div>
      </h5>
      <!-- Form -->
      <form>
        <span class="material-symbols-outlined">mail</span>
        <input type="email" placeholder="Enter your email id">
        <button type="submit"><span class="material-symbols-outlined"><span class="material-symbols-outlined">arrow_right_alt</span>
        </button>
      </form>

      <!-- Icons -->
      <div class="social-icons">
        <i class="fab fa-facebook-f"></i>
        <i class="fab fa-twitter"></i>
        <i class="fab fa-whatsapp"></i>
        <i class="fab fa-pinterest"></i>
      </div>
    </div>
  </div>
  <hr>
 <p class="text-center"> Copyright © Cocoa Abroad Pvt. Ltd. 2022. All rights reserved.</p>
 <p class="text-center">Generated by Elscript Technology</p>
</footer>










